/**
 * SmartAgriculture X - Simulation Engine
 * Simulates ESP32 Server and RS-485 distributed node telemetry in DEMO MODE.
 * Generates realistic fluctuations, responds to hardware commands with physical latency,
 * and maintains the 8 controller node heartbeats.
 */
import {
  NodeStatus,
  SoilZoneReading,
  EnvironmentTelemetry,
  WaterTelemetry,
  PowerTelemetry,
  SecurityTelemetry,
  RoofTelemetry,
  CameraTelemetry,
  NetworkTelemetry,
  Crop,
  FarmEvent,
  SystemSettings
} from '../types';

export const INITIAL_NODES: NodeStatus[] = [
  {
    nodeId: 'N01',
    name: 'Server Coordinator',
    role: 'Central Server, Network Manager, SD Logger, API & RS-485 Router',
    controllerMcu: 'ESP32-WROOM-32UE',
    online: true,
    uptimeSeconds: 184320,
    firmwareVersion: 'v1.4.2-rel',
    freeHeapBytes: 165400,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N02',
    name: 'Agriculture & Crop Manager',
    role: 'Soil, SHT31, Tank, Relays, Crop Advisory Engine',
    controllerMcu: 'ESP32-WROOM-32UE',
    online: true,
    uptimeSeconds: 184318,
    firmwareVersion: 'v1.4.2-rel',
    freeHeapBytes: 142100,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N03',
    name: 'Hybrid Power Node',
    role: 'Solar, Battery, Grid telemetry & Nano failover bus',
    controllerMcu: 'ESP32-WROOM-32UE',
    online: true,
    uptimeSeconds: 184315,
    firmwareVersion: 'v1.4.2-rel',
    freeHeapBytes: 158900,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N04',
    name: 'Roof & Perimeter',
    role: 'N20 DC Motor Actuator, Limit Switches, 4-Beam Optical Laser',
    controllerMcu: 'ESP32-WROOM-32UE',
    online: true,
    uptimeSeconds: 184310,
    firmwareVersion: 'v1.4.2-rel',
    freeHeapBytes: 139800,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N05',
    name: 'TFT Local HMI',
    role: '3.2-inch SPI Display & 7-Button Physical Console',
    controllerMcu: 'ESP32-WROOM-32UE',
    online: true,
    uptimeSeconds: 184290,
    firmwareVersion: 'v1.4.2-rel',
    freeHeapBytes: 188200,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N06',
    name: 'Security Camera',
    role: 'Pan/Tilt Servos, PIR motion detection, RTSP/H.264 IP Stream',
    controllerMcu: 'ESP32-AI Thinker CAM',
    online: true,
    uptimeSeconds: 184250,
    firmwareVersion: 'v1.3.8-cam',
    freeHeapBytes: 98400,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N07',
    name: 'Crop Camera',
    role: 'Fixed Macro Framing, Periodic Image Capture, Time-lapse',
    controllerMcu: 'ESP32-AI Thinker CAM',
    online: true,
    uptimeSeconds: 184240,
    firmwareVersion: 'v1.3.8-cam',
    freeHeapBytes: 104200,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
  {
    nodeId: 'N08',
    name: 'Arduino Nano Relay',
    role: 'Dedicated failover and isolation relay controller',
    controllerMcu: 'Arduino Nano (ATmega328P)',
    online: true,
    uptimeSeconds: 184325,
    firmwareVersion: 'v1.1.0-nano',
    freeHeapBytes: 1024,
    supplyStatus: 'nominal',
    errorCount: 0,
    lastHeartbeat: new Date().toISOString(),
    lastSensorUpdate: new Date().toISOString(),
  },
];

export const INITIAL_CROPS: Crop[] = [
  {
    id: 'crop-rice-01',
    name: 'Rice (Oryza sativa)',
    variety: 'IR64 Premium',
    fieldName: 'Field A',
    plantingDate: '2026-07-01',
    expectedHarvest: '2026-10-28',
    growthStage: 'Vegetative',
    currentDay: 34,
    healthScore: 92,
    todayTask: 'Apply balanced nitrogen-potash fertilizer',
    nextTask: 'Irrigation cycle in 2 days (maintain 5cm water blanket)',
    nextTaskInDays: 2,
    status: 'active',
    notes: 'Tillering stage showing vigorous root spread. Water depth monitored via N02.',
    createdAt: '2026-07-01T06:00:00Z',
    tasks: [
      {
        id: 'task-1',
        cropId: 'crop-rice-01',
        title: 'Apply balanced fertilizer (Urea & Potash)',
        description: 'Broadcast top-dressing fertilizer evenly across Field A.',
        taskType: 'fertilization',
        scheduledDay: 34,
        dueDate: 'Today',
        status: 'pending',
      },
      {
        id: 'task-2',
        cropId: 'crop-rice-01',
        title: 'Deep flood irrigation check',
        description: 'Verify solenoid valve 1 and water level sensor for 5cm submersion.',
        taskType: 'irrigation',
        scheduledDay: 36,
        dueDate: 'In 2 days',
        status: 'pending',
      },
      {
        id: 'task-3',
        cropId: 'crop-rice-01',
        title: 'Stem borer scouting',
        description: 'Visual check and pheromone trap review near perimeter zone 2.',
        taskType: 'pest_control',
        scheduledDay: 40,
        dueDate: 'In 6 days',
        status: 'pending',
      },
      {
        id: 'task-4',
        cropId: 'crop-rice-01',
        title: 'Initial transplanting completed',
        description: '14-day seedling nursery transplantation into flooded paddies.',
        taskType: 'general',
        scheduledDay: 14,
        dueDate: 'Completed',
        status: 'completed',
        completedAt: '2026-07-15T11:00:00Z',
      }
    ],
    images: [
      {
        id: 'img-1',
        cropId: 'crop-rice-01',
        imageUrl: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?auto=format&fit=crop&w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1536657464919-892534f60d6e?auto=format&fit=crop&w=300&q=80',
        captureDate: '2026-09-24T08:00:00Z',
        dayNumber: 33,
        growthStage: 'Vegetative',
        engineeringHealthScore: 92.4,
        leafGreennessIndex: 0.84,
        illuminationLux: 54200,
        notes: 'ESP32-CAM N07 daily morning macro. Optimal leaf coloration detected.',
      },
      {
        id: 'img-2',
        cropId: 'crop-rice-01',
        imageUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=300&q=80',
        captureDate: '2026-09-17T08:00:00Z',
        dayNumber: 26,
        growthStage: 'Vegetative',
        engineeringHealthScore: 89.8,
        leafGreennessIndex: 0.81,
        illuminationLux: 48900,
        notes: 'Week 4 evaluation. Canopy density increased by 18%.',
      },
      {
        id: 'img-3',
        cropId: 'crop-rice-01',
        imageUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=300&q=80',
        captureDate: '2026-09-03T08:00:00Z',
        dayNumber: 12,
        growthStage: 'Seedling',
        engineeringHealthScore: 88.0,
        leafGreennessIndex: 0.77,
        illuminationLux: 51200,
        notes: 'Post-transplanting establishment phase.',
      }
    ]
  },
  {
    id: 'crop-tomato-02',
    name: 'Greenhouse Tomatoes',
    variety: 'San Marzano Hybrid',
    fieldName: 'Bed 2 (Automated Roof)',
    plantingDate: '2026-08-10',
    expectedHarvest: '2026-11-15',
    growthStage: 'Flowering',
    currentDay: 46,
    healthScore: 95,
    todayTask: 'Inspect trellising & prune suckers',
    nextTask: 'Calcium nitrate foliar spray in 3 days',
    nextTaskInDays: 3,
    status: 'active',
    notes: 'Protected under automated roof N04. Rain sensor interlock enabled.',
    createdAt: '2026-08-10T06:00:00Z',
    tasks: [
      {
        id: 'task-t1',
        cropId: 'crop-tomato-02',
        title: 'Inspect trellising & lateral branch pruning',
        description: 'Maintain single leader stem for optimal airflow.',
        taskType: 'pruning',
        scheduledDay: 46,
        dueDate: 'Today',
        status: 'pending',
      },
      {
        id: 'task-t2',
        cropId: 'crop-tomato-02',
        title: 'Calcium nitrate supplementation',
        description: 'Prevent blossom end rot during high flower set.',
        taskType: 'fertilization',
        scheduledDay: 49,
        dueDate: 'In 3 days',
        status: 'pending',
      }
    ],
    images: [
      {
        id: 'img-t1',
        cropId: 'crop-tomato-02',
        imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=300&q=80',
        captureDate: '2026-09-24T09:30:00Z',
        dayNumber: 45,
        growthStage: 'Flowering',
        engineeringHealthScore: 95.1,
        leafGreennessIndex: 0.88,
        illuminationLux: 62000,
        notes: 'Profuse flowering clusters on third truss.',
      }
    ]
  }
];

export const INITIAL_EVENTS: FarmEvent[] = [
  {
    id: 'evt-001',
    timestamp: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    eventType: 'NODE_ONLINE',
    nodeId: 'N01',
    severity: 'info',
    description: 'Server ESP32-WROOM-32UE initialized RS-485 bus master sequence',
    status: 'logged',
  },
  {
    id: 'evt-002',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    eventType: 'POWER_SOURCE_CHANGED',
    nodeId: 'N03',
    severity: 'info',
    description: 'Power source shifted to Solar PV (2.42 kW generation active)',
    status: 'logged',
  },
  {
    id: 'evt-003',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    eventType: 'NETWORK_CHANGED',
    nodeId: 'N01',
    severity: 'info',
    description: 'Network active priority: LAN connected (100 Mbps W5500)',
    status: 'logged',
  },
  {
    id: 'evt-004',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    eventType: 'ROOF_CLOSED',
    nodeId: 'N04',
    severity: 'info',
    description: 'Automatic roof closed safely at limit switch. Limit status verified.',
    status: 'resolved',
  },
  {
    id: 'evt-005',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    eventType: 'CROP_TASK_DUE',
    nodeId: 'N02',
    severity: 'info',
    description: 'Crop task due: Rice Field A Day 34 fertilization schedule',
    status: 'logged',
  },
  {
    id: 'evt-006',
    timestamp: new Date(Date.now() - 1000 * 60 * 210).toISOString(),
    eventType: 'SYNC_COMPLETED',
    nodeId: 'N01',
    severity: 'info',
    description: 'Offline microSD buffer synchronized 48 queued telemetry frames to Cloud',
    status: 'resolved',
  }
];

export const INITIAL_SETTINGS: SystemSettings = {
  farmName: 'SmartAgriculture Green Horizon Station',
  moistureLowThreshold: 35.0,
  moistureHighThreshold: 75.0,
  temperatureHighThreshold: 35.0,
  tankLowThreshold: 20.0,
  autoIrrigationEnabled: true,
  autoRoofRainProtection: true,
  autoSolarTracking: true,
  securityArmed: true,
  cloudSyncIntervalSeconds: 10,
  esp32ServerIp: '192.168.1.100',
  esp32ApiPort: 80,
  esp32WsPort: 81,
  demoModeActive: true,
};
